-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKiUgBiLqc2lWi3FQ
QU6QjExjX9CMYEcshIis9pdXA9SgCgYIKoZIzj0DAQehRANCAARmknR58FGIi3fy
7VyDrMiX5NHEzdMzyM2ZW1oGgPO8qYMWK/4eGQWND3vr6lCVtJpXPt+ZURInfAgf
SRCwHGmy
-----END PRIVATE KEY-----